test_that("check dimension values", {
  expect_true(check_dimensionType("area"))
  expect_true(check_dimensionType(c("area")))
  expect_true(check_dimensionType(c("area", "area")))
  expect_true(check_dimensionType("depth"))
  expect_true(check_dimensionType(c("depth")))
  expect_true(check_dimensionType(c("depth", "depth")))
  expect_true(check_dimensionType("width"))
  expect_true(check_dimensionType(c("width")))
  expect_true(check_dimensionType(c("width", "width")))
  expect_true(check_dimensionType("discharge"))
  expect_true(check_dimensionType(c("discharge")))
  expect_true(check_dimensionType(c("discharge", "discharge")))
  expect_true(check_dimensionType(c("area", "width", "depth")))
  expect_true(check_dimensionType(c("area", "width", "depth", "discharge")))
})

test_that("check errors", {
  expect_error(check_dimensionType("Area"))
  expect_error(check_dimensionType("height"))
  expect_error(check_dimensionType(7))
  expect_error(check_dimensionType(c("area", "Yo Mamma")))
})
